#ifndef GLOBALS_H
#define GLOBALS_H

#define I2C_ADDRESS 8
#define ESCON_RPM_RANGE_MIN -6000
#define ESCON_RPM_RANGE_MAX 6000
#define NUM_WHEELS 6


#define LEFT_FRONT_WHEEL_SET_SPEED 23
#define LEFT_FRONT_WHEEL_DIR 23
#define LEFT_FRONT_WHEEL_ENABLE 23
#define LEFT_FRONT_WHEEL_ACTUAL_SPEED 23
#define LEFT_FRONT_WHEEL_ERROR 23

#define LEFT_MIDDLE_WHEEL_SET_SPEED 23
#define LEFT_MIDDLE_WHEEL_DIR 23
#define LEFT_MIDDLE_WHEEL_ENABLE 23
#define LEFT_MIDDLE_WHEEL_ACTUAL_SPEED 23
#define LEFT_MIDDLE_WHEEL_ERROR 23

#define LEFT_REAR_WHEEL_SET_SPEED 23
#define LEFT_REAR_WHEEL_DIR 23
#define LEFT_REAR_WHEEL_ENABLE 23
#define LEFT_REAR_WHEEL_ACTUAL_SPEED 23
#define LEFT_REAR_WHEEL_ERROR 23

#define RIGHT_FRONT_WHEEL_SET_SPEED 7
#define RIGHT_FRONT_WHEEL_DIR 3
#define RIGHT_FRONT_WHEEL_ENABLE 5
#define RIGHT_FRONT_WHEEL_ACTUAL_SPEED A0
#define RIGHT_FRONT_WHEEL_ERROR 1

#define RIGHT_MIDDLE_WHEEL_SET_SPEED 23
#define RIGHT_MIDDLE_WHEEL_DIR 23
#define RIGHT_MIDDLE_WHEEL_ENABLE 23
#define RIGHT_MIDDLE_WHEEL_ACTUAL_SPEED 23
#define RIGHT_MIDDLE_WHEEL_ERROR 23

#define RIGHT_REAR_WHEEL_SET_SPEED 23
#define RIGHT_REAR_WHEEL_DIR 23
#define RIGHT_REAR_WHEEL_ENABLE 23
#define RIGHT_REAR_WHEEL_ACTUAL_SPEED 23
#define RIGHT_REAR_WHEEL_ERROR 23

#endif
