#ifndef GLOBALS_H
#define GLOBALS_H

#include <Arduino.h>

const int I2C_ADDRESS = 8;
const int ESCON_RPM_RANGE_MIN = -6000;
const int ESCON_RPM_RANGE_MAX = 6000;
const int NUM_WHEELS = 6;

const int LEFT_FRONT_WHEEL_SET_SPEED = 45;
const int LEFT_FRONT_WHEEL_ENABLE = 49;
const int LEFT_FRONT_WHEEL_DIR = 53;
const int LEFT_FRONT_WHEEL_ERROR = 51;
const int LEFT_FRONT_WHEEL_ACTUAL_SPEED = A15;
const int LEFT_FRONT_WHEEL_ACCELERATION = //TODO;
const int LEFT_FRONT_WHEEL_DECELERATION = //TODO;


const int LEFT_MIDDLE_WHEEL_SET_SPEED = 46;
const int LEFT_MIDDLE_WHEEL_ENABLE = 48;
const int LEFT_MIDDLE_WHEEL_DIR = 50;
const int LEFT_MIDDLE_WHEEL_ERROR = 52;
const int LEFT_MIDDLE_WHEEL_ACTUAL_SPEED = A9;
const int LEFT_MIDDLE_WHEEL_ACCELERATION = //TODO;
const int LEFT_MIDDLE_WHEEL_DECELERATION = //TODO;

const int LEFT_REAR_WHEEL_SET_SPEED = 44;
const int LEFT_REAR_WHEEL_ENABLE = 38;
const int LEFT_REAR_WHEEL_DIR = 40;
const int LEFT_REAR_WHEEL_ERROR = 42;
const int LEFT_REAR_WHEEL_ACTUAL_SPEED = A3;
const int LEFT_REAR_WHEEL_ACCELERATION = //TODO;
const int LEFT_REAR_WHEEL_DECELERATION = //TODO;

const int RIGHT_REAR_WHEEL_SET_SPEED = 2;
const int RIGHT_REAR_WHEEL_ENABLE = 27;
const int RIGHT_REAR_WHEEL_DIR = 25;
const int RIGHT_REAR_WHEEL_ERROR = 23;
const int RIGHT_REAR_WHEEL_ACTUAL_SPEED = A6;
const int RIGHT_REAR_WHEEL_ACCELERATION = //TODO;
const int RIGHT_REAR_WHEEL_DECELERATION = //TODO;

const int RIGHT_MIDDLE_WHEEL_SET_SPEED = 3;
const int RIGHT_MIDDLE_WHEEL_ENABLE = 24;
const int RIGHT_MIDDLE_WHEEL_DIR = 26;
const int RIGHT_MIDDLE_WHEEL_ERROR = 28;
const int RIGHT_MIDDLE_WHEEL_ACTUAL_SPEED = A12;
const int RIGHT_MIDDLE_WHEEL_ACCELERATION = //TODO;
const int RIGHT_MIDDLE_WHEEL_DECELERATION = //TODO;

const int RIGHT_FRONT_WHEEL_SET_SPEED = 4;
const int RIGHT_FRONT_WHEEL_ENABLE = 5;
const int RIGHT_FRONT_WHEEL_DIR = 6;
const int RIGHT_FRONT_WHEEL_ERROR = 7;
const int RIGHT_FRONT_WHEEL_ACTUAL_SPEED = A10;
const int RIGHT_FRONT_WHEEL_ACCELERATION = //TODO;
const int RIGHT_FRONT_WHEEL_DECELERATION = //TODO;


const uint8_t SHOULDER_ADDRESS = 11;
const uint8_t ELBOW_ADDRESS = 12;
const uint8_t WRIST_ADDRESS = 13;
//
////hand h-bridge pins
//const int HAND_PWM = 10;
//const int HAND_LN_B = 43;
//const int HAND_LN_A = 42;
//
////finger h-bridge pins
//const int FINGER_PWM = 9;
//const int FINGER_LN_A = 40;
//const int FINGER_LN_B = 41;

//const int JETSON_POWER_ON = 44;

//const int ARM_TURRET = 8;
//const int ARM_TURRET_FB = A14;

const int POWER_INDICATOR = 13;

const int TURRET_ADDRESS = 15;

#endif
