#ifndef GLOBALS_H
#define GLOBALS_H

#define I2C_ADDRESS 8
#define ESCON_RPM_RANGE_MIN -6000
#define ESCON_RPM_RANGE_MAX 6000
#define NUM_WHEELS 6


#define LEFT_FRONT_WHEEL_SET_SPEED 2
#define LEFT_FRONT_WHEEL_ENABLE 22
#define LEFT_FRONT_WHEEL_DIR 28
#define LEFT_FRONT_WHEEL_ERROR 34
#define LEFT_FRONT_WHEEL_ACTUAL_SPEED A8

#define LEFT_MIDDLE_WHEEL_SET_SPEED 3
#define LEFT_MIDDLE_WHEEL_ENABLE 23
#define LEFT_MIDDLE_WHEEL_DIR 29
#define LEFT_MIDDLE_WHEEL_ERROR 35
#define LEFT_MIDDLE_WHEEL_ACTUAL_SPEED A9

#define LEFT_REAR_WHEEL_SET_SPEED 4
#define LEFT_REAR_WHEEL_ENABLE 24
#define LEFT_REAR_WHEEL_DIR 30
#define LEFT_REAR_WHEEL_ERROR 36
#define LEFT_REAR_WHEEL_ACTUAL_SPEED A10

#define RIGHT_REAR_WHEEL_SET_SPEED 5
#define RIGHT_REAR_WHEEL_ENABLE 25
#define RIGHT_REAR_WHEEL_DIR 31
#define RIGHT_REAR_WHEEL_ERROR 37
#define RIGHT_REAR_WHEEL_ACTUAL_SPEED A11

#define RIGHT_MIDDLE_WHEEL_SET_SPEED 6
#define RIGHT_MIDDLE_WHEEL_ENABLE 26
#define RIGHT_MIDDLE_WHEEL_DIR 32
#define RIGHT_MIDDLE_WHEEL_ERROR 38
#define RIGHT_MIDDLE_WHEEL_ACTUAL_SPEED A12

#define RIGHT_FRONT_WHEEL_SET_SPEED 7
#define RIGHT_FRONT_WHEEL_ENABLE 27
#define RIGHT_FRONT_WHEEL_DIR 33
#define RIGHT_FRONT_WHEEL_ERROR 39
#define RIGHT_FRONT_WHEEL_ACTUAL_SPEED A13


#define SHOULDER_ADDRESS 11
#define ELBOW_ADDRESS 12
#define WRIST_ADDRESS 13
#define LEFT_HAND_PWM 9
#define RIGHT_HAND_PWM 10
#define LEFT_HAND_LN_A 40
#define LEFT_HAND_LN_B 41
#define RIGHT_HAND_LN_A 42
#define RIGHT_HAND_LN_B 43



#endif
